version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: xcodebuild test -scheme PingaApp -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5' -configuration 'Debug'

workflows:
    test-workflow:
      jobs:
        - test:
            filters:
              branches:
                only:
                 - main
                 - dev
        
